[[redirects]]
  from = "/https://resonance-test.netlify.app
  to = "https://mock-school-backend.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"